name: Corgis NFT contract & app CI/CD

on:
  # We want to trigger the build & test pipelines in every branch.
  # This will help us to detect errors earlier in the development process.
  push:
    # But do no run the pipeline when only `md` files are modified.
    paths-ignore:
      - '**.md'
  # We also want to trigger the pipeline on every PR.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # For more information, take a look at https://github.com/near/near-cli/blob/master/utils/eventtracking.js
    - name: Disable near-cli event tracking consent question (which block the CI pipeline)
      run: "mkdir $HOME/.near-config && echo '{\"trackingEnabled\": false, \"trackingAccountID\": false}' > $HOME/.near-config/settings.json"
      
    - name: Install Rust target wasm32 to compile for the NEAR platform
      run: rustup target add wasm32-unknown-unknown

    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build the Rust Corgis contract
      run: yarn build:contract
      
    - name: Run unit tests for the Rust Corgis contract locally
      run: yarn test:contract
    
    - name: Deploy the Rust Corgis contract to testnet using a dev account
      run: yarn dev-deploy:contract
      continue-on-error: true
      
    - name: Run API tests for the Rust Corgis contract against testnet using the dev account
      run: yarn api-test:contract
      continue-on-error: true

    - name: Generate key the account to be used by gh-pages (only in master)
      run: yarn near generate-key corgis-nft.testnet --seedPhrase="$seed_phrase"
      env:
        seed_phrase: ${{ secrets.SEED_PHRASE }}
      if: ${{ github.ref == 'refs/heads/master' }}
    
    - name: Set up origin to be able to push to gh-pages (only in master)
      run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.ref == 'refs/heads/master' }}
      
    - name: Deploy the Rust Corgis contract to testnet and the React app to gh-pages (only in master)
      run: CONTRACT_NAME=corgis-nft.testnet yarn deploy
      if: ${{ github.ref == 'refs/heads/master' }}
